INSERT INTO category (description) VALUES('American')
INSERT INTO category (description) VALUES('Italian')
INSERT INTO category (description) VALUES('Turk')
INSERT INTO category (description) VALUES('Chinese')
INSERT INTO unit_of_measure (description) VALUES('Cay Kaşığı')
INSERT INTO unit_of_measure (description) VALUES('Yemek Kaşığı')
INSERT INTO unit_of_measure (description) VALUES('Kepçe')
INSERT INTO unit_of_measure (description) VALUES('Su Bardağı')